"""removed_is_suspicious_column

Revision ID: 49e450d7eca0
Revises: cb7484962014
Create Date: 2026-07-08 14:47:07.600211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e450d7eca0'
down_revision: Union[str, Sequence[str], None] = 'cb7484962014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'is_suspicious')
    op.add_column('users', sa.Column('is_suspicious', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspicious')
    op.add_column('refresh_tokens', sa.Column('is_suspicious', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
