"""add citext to email

Revision ID: 3fde3a399b65
Revises: 49e450d7eca0
Create Date: 2026-09-18 11:31:01.098499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fde3a399b65'
down_revision: Union[str, Sequence[str], None] = '49e450d7eca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
